linters-settings:
  wrapcheck:
    ignorePackageGlobs:
      - github.com/satisfactorymodding/SatisfactoryModManager/*

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gocritic:
    disabled-checks:
      - ifElseChain

  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/satisfactorymodding/SatisfactoryModManager)
      - blank
      - dot

issues:
  exclude-rules:
    - linters:
        - typecheck
      text: "no matching files found"
  exclude-dirs:
    - frontend

run:
  timeout: 5m
  build-tags:
    - webkit2_41

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bidichk
    - contextcheck
    - durationcheck
    - errorlint
    - goconst
    - goimports
    - revive
    - misspell
    - prealloc
    - whitespace
    - wrapcheck
    - gci
    - gocritic
    - gofumpt
    - nonamedreturns
