version: "2"
run:
  build-tags:
    - webkit2_41
linters:
  default: none
  enable:
    - bidichk
    - contextcheck
    - durationcheck
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nonamedreturns
    - prealloc
    - revive
    - staticcheck
    - unused
    - whitespace
    - wrapcheck
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    wrapcheck:
      ignore-package-globs:
        - github.com/satisfactorymodding/SatisfactoryModManager/*
    revive:
      rules:
        - name: var-naming
          arguments:
            - [ ] # AllowList
            - [ ] # DenyList
            - - skip-package-name-checks: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - frontend
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/satisfactorymodding/SatisfactoryModManager)
        - blank
        - dot
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - frontend
