// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ficsitcli_bindings} from '../models';
import {cli} from '../models';
import {context} from '../models';

export function AddProfile(arg1:string):Promise<Error>;

export function CheckForUpdates():Promise<Array<ficsitcli_bindings.Update>>;

export function DeleteProfile(arg1:string):Promise<Error>;

export function DisableMod(arg1:string):Promise<Error>;

export function EnableMod(arg1:string):Promise<Error>;

export function ExportCurrentProfile():Promise<Error>;

export function GetInstallation(arg1:string):Promise<ficsitcli_bindings.InstallationInfo>;

export function GetInstallationsInfo():Promise<Array<ficsitcli_bindings.InstallationInfo>>;

export function GetInvalidInstalls():Promise<Array<string>>;

export function GetLockFile(arg1:ficsitcli_bindings.InstallationInfo):Promise<cli.LockFile>;

export function GetProfile(arg1:string):Promise<cli.Profile>;

export function GetProfiles():Promise<Array<string>>;

export function GetSelectedInstall():Promise<ficsitcli_bindings.InstallationInfo>;

export function GetSelectedProfile():Promise<any>;

export function ImportProfile(arg1:string,arg2:string):Promise<Error>;

export function Init():Promise<Error>;

export function InstallMod(arg1:string):Promise<Error>;

export function InstallModVersion(arg1:string,arg2:string):Promise<Error>;

export function LaunchGame():Promise<void>;

export function MakeCurrentExportedProfile():Promise<ficsitcli_bindings.ExportedProfile>;

export function ReadExportedProfileMetadata(arg1:string):Promise<ficsitcli_bindings.ExportedProfileMetadata>;

export function RemoveMod(arg1:string):Promise<Error>;

export function RenameProfile(arg1:string,arg2:string):Promise<Error>;

export function SelectInstall(arg1:string):Promise<Error>;

export function SetProfile(arg1:string):Promise<Error>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateAllMods():Promise<Error>;
