// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['AddProfile'](arg1);
}

export function CheckForUpdates() {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['CheckForUpdates']();
}

export function DeleteProfile(arg1) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['DeleteProfile'](arg1);
}

export function DisableMod(arg1) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['DisableMod'](arg1);
}

export function EnableMod(arg1) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['EnableMod'](arg1);
}

export function ExportCurrentProfile() {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['ExportCurrentProfile']();
}

export function GetInstallation(arg1) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['GetInstallation'](arg1);
}

export function GetInstallationsInfo() {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['GetInstallationsInfo']();
}

export function GetInvalidInstalls() {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['GetInvalidInstalls']();
}

export function GetLockFile(arg1) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['GetLockFile'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['GetProfile'](arg1);
}

export function GetProfiles() {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['GetProfiles']();
}

export function GetSelectedInstall() {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['GetSelectedInstall']();
}

export function GetSelectedProfile() {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['GetSelectedProfile']();
}

export function ImportProfile(arg1, arg2) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['ImportProfile'](arg1, arg2);
}

export function Init() {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['Init']();
}

export function InstallMod(arg1) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['InstallMod'](arg1);
}

export function InstallModVersion(arg1, arg2) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['InstallModVersion'](arg1, arg2);
}

export function LaunchGame() {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['LaunchGame']();
}

export function MakeCurrentExportedProfile() {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['MakeCurrentExportedProfile']();
}

export function ReadExportedProfileMetadata(arg1) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['ReadExportedProfileMetadata'](arg1);
}

export function RemoveMod(arg1) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['RemoveMod'](arg1);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['RenameProfile'](arg1, arg2);
}

export function SelectInstall(arg1) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['SelectInstall'](arg1);
}

export function SetProfile(arg1) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['SetProfile'](arg1);
}

export function Startup(arg1) {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['Startup'](arg1);
}

export function UpdateAllMods() {
  return window['go']['ficsitcli_bindings']['FicsitCLI']['UpdateAllMods']();
}
