name: 'goreleaser'
description: 'Download and run goreleaser'
inputs:
  args:
    description: 'goreleaser arguments'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download goreleaser
      if: runner.os == 'Windows'
      run: |
        gh release download --repo mircearoata/goreleaser --pattern "goreleaser-windows.exe" --output "$(go env GOPATH)/bin/goreleaser.exe"
      shell: powershell
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Download goreleaser
      if: runner.os == 'Linux'
      run: |
        gh release download --repo mircearoata/goreleaser --pattern "goreleaser-linux" --output "$(go env GOPATH)/bin/goreleaser"
        chmod +x $(go env GOPATH)/bin/goreleaser
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Download goreleaser
      if: runner.os == 'macOS'
      shell: bash
      run: |
        gh release download --repo mircearoata/goreleaser --pattern "goreleaser-darwin" --output "$(go env GOPATH)/bin/goreleaser"
        chmod +x $(go env GOPATH)/bin/goreleaser
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Run GoReleaser ${{ inputs.goreleaser_args }}
      shell: bash
      run: goreleaser ${{ inputs.args }}

