// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExpandMod() {
  return window['go']['bindings']['App']['ExpandMod']();
}

export function GetVersion() {
  return window['go']['bindings']['App']['GetVersion']();
}

export function OpenFileDialog(arg1) {
  return window['go']['bindings']['App']['OpenFileDialog'](arg1);
}

export function UnexpandMod() {
  return window['go']['bindings']['App']['UnexpandMod']();
}
