// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function ExpandMod():Promise<boolean>;

export function GetVersion():Promise<string>;

export function OpenFileDialog(arg1:bindings.OpenDialogOptions):Promise<string>;

export function UnexpandMod():Promise<boolean>;
