// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['bindings']['FicsitCLI']['AddProfile'](arg1);
}

export function CheckForUpdates() {
  return window['go']['bindings']['FicsitCLI']['CheckForUpdates']();
}

export function DeleteProfile(arg1) {
  return window['go']['bindings']['FicsitCLI']['DeleteProfile'](arg1);
}

export function DisableMod(arg1) {
  return window['go']['bindings']['FicsitCLI']['DisableMod'](arg1);
}

export function EnableMod(arg1) {
  return window['go']['bindings']['FicsitCLI']['EnableMod'](arg1);
}

export function GetCurrentLockfile(arg1) {
  return window['go']['bindings']['FicsitCLI']['GetCurrentLockfile'](arg1);
}

export function GetInstallation(arg1) {
  return window['go']['bindings']['FicsitCLI']['GetInstallation'](arg1);
}

export function GetInstallationsInfo() {
  return window['go']['bindings']['FicsitCLI']['GetInstallationsInfo']();
}

export function GetInvalidInstalls() {
  return window['go']['bindings']['FicsitCLI']['GetInvalidInstalls']();
}

export function GetProfile(arg1) {
  return window['go']['bindings']['FicsitCLI']['GetProfile'](arg1);
}

export function GetProfiles() {
  return window['go']['bindings']['FicsitCLI']['GetProfiles']();
}

export function GetSelectedInstall() {
  return window['go']['bindings']['FicsitCLI']['GetSelectedInstall']();
}

export function GetSelectedProfile() {
  return window['go']['bindings']['FicsitCLI']['GetSelectedProfile']();
}

export function InstallMod(arg1) {
  return window['go']['bindings']['FicsitCLI']['InstallMod'](arg1);
}

export function InstallModVersion(arg1, arg2) {
  return window['go']['bindings']['FicsitCLI']['InstallModVersion'](arg1, arg2);
}

export function RemoveMod(arg1) {
  return window['go']['bindings']['FicsitCLI']['RemoveMod'](arg1);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['bindings']['FicsitCLI']['RenameProfile'](arg1, arg2);
}

export function SelectInstall(arg1) {
  return window['go']['bindings']['FicsitCLI']['SelectInstall'](arg1);
}

export function SetProfile(arg1) {
  return window['go']['bindings']['FicsitCLI']['SetProfile'](arg1);
}

export function SetProgress(arg1) {
  return window['go']['bindings']['FicsitCLI']['SetProgress'](arg1);
}

export function UpdateAllMods() {
  return window['go']['bindings']['FicsitCLI']['UpdateAllMods']();
}
