// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {cli} from '../models';

export function AddProfile(arg1:string):Promise<Error>;

export function CheckForUpdates():Promise<Array<bindings.Update>>;

export function DeleteProfile(arg1:string):Promise<Error>;

export function DisableMod(arg1:string):Promise<Error>;

export function EnableMod(arg1:string):Promise<Error>;

export function ExportCurrentProfile():Promise<Error>;

export function GetCurrentLockfile(arg1:bindings.InstallationInfo):Promise<cli.LockFile>;

export function GetInstallation(arg1:string):Promise<bindings.InstallationInfo>;

export function GetInstallationsInfo():Promise<Array<bindings.InstallationInfo>>;

export function GetInvalidInstalls():Promise<Array<string>>;

export function GetProfile(arg1:string):Promise<cli.Profile>;

export function GetProfiles():Promise<Array<string>>;

export function GetSelectedInstall():Promise<bindings.InstallationInfo>;

export function GetSelectedProfile():Promise<any>;

export function ImportProfile(arg1:string,arg2:string):Promise<Error>;

export function InstallMod(arg1:string):Promise<Error>;

export function InstallModVersion(arg1:string,arg2:string):Promise<Error>;

export function ReadExportedProfileMetadata(arg1:string):Promise<bindings.ExportedProfileMetadata>;

export function RemoveMod(arg1:string):Promise<Error>;

export function RenameProfile(arg1:string,arg2:string):Promise<Error>;

export function SelectInstall(arg1:string):Promise<void>;

export function SetProfile(arg1:string):Promise<void>;

export function SetProgress(arg1:bindings.Progress):Promise<void>;

export function UpdateAllMods():Promise<Error>;
