// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project_file} from '../models';

export function GetProjectFile():Promise<project_file.Project>;
