// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FavouriteMod(arg1) {
  return window['go']['bindings']['Settings']['FavouriteMod'](arg1);
}

export function GetFavouriteMods() {
  return window['go']['bindings']['Settings']['GetFavouriteMods']();
}

export function GetModFiltersFilter() {
  return window['go']['bindings']['Settings']['GetModFiltersFilter']();
}

export function GetModFiltersOrder() {
  return window['go']['bindings']['Settings']['GetModFiltersOrder']();
}

export function GetStartView() {
  return window['go']['bindings']['Settings']['GetStartView']();
}

export function SetModFiltersFilter(arg1) {
  return window['go']['bindings']['Settings']['SetModFiltersFilter'](arg1);
}

export function SetModFiltersOrder(arg1) {
  return window['go']['bindings']['Settings']['SetModFiltersOrder'](arg1);
}

export function SetStartView(arg1) {
  return window['go']['bindings']['Settings']['SetStartView'](arg1);
}

export function UnFavouriteMod(arg1) {
  return window['go']['bindings']['Settings']['UnFavouriteMod'](arg1);
}
