// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function GetModFilters():Promise<bindings.SavedModFilters>;

export function SetModFilters(arg1:string,arg2:string):void;

export function UnFavouriteMod(arg1:string):Promise<boolean>;

export function FavouriteMod(arg1:string):Promise<boolean>;

export function GetFavouriteMods():Promise<Array<string>>;
