// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FavouriteMod(arg1) {
  return window['go']['bindings']['Settings']['FavouriteMod'](arg1);
}

export function GetFavouriteMods() {
  return window['go']['bindings']['Settings']['GetFavouriteMods']();
}

export function GetModFilters() {
  return window['go']['bindings']['Settings']['GetModFilters']();
}

export function SetModFilters(arg1, arg2) {
  return window['go']['bindings']['Settings']['SetModFilters'](arg1, arg2);
}

export function UnFavouriteMod(arg1) {
  return window['go']['bindings']['Settings']['UnFavouriteMod'](arg1);
}
