// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FavouriteMod(arg1:string):Promise<boolean>;

export function GetFavouriteMods():Promise<Array<string>>;

export function GetModFiltersFilter():Promise<string>;

export function GetModFiltersOrder():Promise<string>;

export function GetStartView():Promise<string>;

export function SetModFiltersFilter(arg1:string):Promise<void>;

export function SetModFiltersOrder(arg1:string):Promise<void>;

export function SetStartView(arg1:string):Promise<void>;

export function UnFavouriteMod(arg1:string):Promise<boolean>;
