query GetModDetails($modReference: ModReference!) {
  mod: getModByReference(modReference: $modReference) {
    ...ModKey
    name
    logo
    logo_thumbhash
    mod_reference
    full_description
    created_at
    last_version_date
    downloads
    views
    hidden
    compatibility {
      Controller {
        state
        note
      }
      EA {
        state
        note
      }
      EXP {
        state
        note
      }
    }
    ai_use_disclosure {
      disclosure_type
      message
    }
    authors {
      user {
        id
        username
        avatar
      }
      role
    }
    versions(filter: {limit: 100}) {
      id
      version
      size
      changelog
    }
  }
}
