on:
  workflow_call:
    inputs:
      goreleaser_args:
        required: false
        type: string
        default: --snapshot
    secrets:
      SIGNPATH_API_TOKEN:
        required: true

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: linux
            # This should use distros as old as possible to maximize glibc compatibility
            # Ubuntu 22.04's glibc doesn't really cover all non-EOL distros, but as far as I can tell it happens to be
            # the oldest non-EOL distro version which has webkit2gtk-4.1, so it will have to do, and we can hope it covers
            # all distros and versions people would reasonably install SMM on
            runs-on: ubuntu-22.04
            # We also use a custom webkit2gtk-4.1 built against freetype 2.13 
            # as a fix for appimage crashes on distros using versions newer than that when displaying emoji
            # Running webkit2gtk-4.1 built against this newer version should be safe on older distros too,
            # since the struct causing the crash is larger in newer versions
            container: ghcr.io/${{ github.repository_owner }}/smm-builder:ubuntu22.04
          - os: windows
            # Using windows-2022 for now because NSIS is missing on windows-2025 runners
            runs-on: windows-2022
            goreleaser_args: "-p 1" # Wails packaging for windows cannot handle parallel builds
          - os: darwin
            runs-on: macos-15
            goreleaser_args: "-p 1" # Wails packaging for darwin cannot handle parallel builds
    runs-on: ${{ matrix.platform.runs-on }}
    container: ${{ matrix.platform.container || null }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
    
      # When running in a container, the user is root, but the workspace is mounted from the host, so git commands will fail unless we set the safe directory
      # https://github.com/actions/checkout/issues/2031
      - name: Set safe directory
        run: git config --system --add safe.directory "$GITHUB_WORKSPACE"

      - uses: ./.github/actions/setup

      - name: Install Task
        uses: go-task/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser ${{ inputs.goreleaser_args }}
        uses: ./.github/actions/goreleaser
        with:
          args: release --split --clean ${{ matrix.platform.goreleaser_args }} ${{ inputs.goreleaser_args }}
        env:
          GGOOS: ${{ matrix.platform.os }}

      - name: Archive artifacts
        id: upload_artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-${{ matrix.platform.os }}
          path: dist/**/*

      - name: Sign artifacts
        id: sign_windows
        if: ${{ matrix.platform.os == 'windows' && startsWith(github.ref, 'refs/tags/') }}
        uses: signpath/github-action-submit-signing-request@v2
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: 'd1f0888a-08d3-44fe-9da0-6490890e20ea'
          project-slug: 'SatisfactoryModManager'
          signing-policy-slug: 'release-signing'
          github-artifact-id: '${{ steps.upload_artifacts.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: 'dist/signed'

      - name: Archive signed artifacts
        if: ${{ matrix.platform.os == 'windows' && startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v7
        with:
          name: build-${{ matrix.platform.os }}
          path: dist/signed/**/*
          overwrite: true

  finalize:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup
        with:
          backend: false
          frontend: false

      - name: Download windows artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-windows
          path: dist

      - name: Download linux artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-linux
          path: dist

      - name: Download darwin artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-darwin
          path: dist

      - name: Run GoReleaser Merge ${{ inputs.goreleaser_args }}
        uses: ./.github/actions/goreleaser
        with:
          args: continue --merge ${{ inputs.goreleaser_args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-all
          path: dist/**/*
